platform:ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target "XKPSDeliver" do
pod 'UMengUShare', '~> 6.2.2'
pod 'UMengAnalytics', '~> 4.2.4'
pod 'AFNetworking', '~> 3.1.0'
pod “IQKeyboardManager”, “3.3.5”
pod “Reachability”,”3.2”
pod “SDWebImage”, “3.7.4”
pod 'MBProgressHUD', '~> 1.0.0'
pod “MJExtension”,”3.0.10”
pod “ZBarSDK”,”1.3.1”
pod 'MJRefresh', '~> 3.1.12'
pod 'YYText', '~> 1.0.7'
pod 'RegexKitLite', '~> 4.0'
pod 'PNChart', '~> 0.8.9'
pod 'JSPatchPlatform'
pod 'BaiduMapKit'
pod 'SCLAlertView-Objective-C', '~> 1.1.0'
pod 'Shimmer', '~> 1.0.2'
pod 'JKCategories', '~> 1.5'
pod 'BPushSDK', '~> 1.4.8'
pod 'AsyncDisplayKit', '~> 2.1'
pod 'YYWebImage'
pod 'ReactiveCocoa','~>2.5'
end
